# Dockerfile.build
FROM node:18-alpine AS build

WORKDIR /app
COPY . .

RUN yarn install
RUN yarn build

FROM node:18-alpine

WORKDIR /app

COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY package.json ./
COPY yarn.lock ./

RUN yarn install

CMD ["yarn", "start"]