export default {
  text: 'var(--black-black900)',
  'text-on-button': 'var(--white-white900)',
  'text-on-button-disabled': 'var(--gray-gray300)',
  'text-hint': 'var(--gray-gray700)',
  'text-link': 'var(--blue-blue600)',
  'text-link-pressed': 'var(--blue-blue800)',
  'text-on-button-bold': 'var(--blue-blue600)',
  'text-on-button-danger': 'var(--red-red500)',
  'text-danger': 'var(--red-red500)',
  'text-positive': 'var(--green-green800)',

  'iсon-on-color': 'var(--white-white900)',
  'icon-neutral': 'var(--gray-gray600)',
  'iсon-on-neutral': 'var(--gray-gray900)',
  'icon-link': 'var(--blue-blue600)',

  'border-active': 'var(--blue-blue600)',
  'border-danger': 'var(--red-red500)',
  'border-separator': 'var(--gray-gray100)',
  'border-icon-accent-tertiary': 'var(--violet-violet400)',
  'border-icon-accent-secondary': 'var(--green-green400)',
  'border-icon-accent-primary': 'var(--blue-blue400)',

  'bg-primary': 'var(--gray-gray50)',
  'bg-input': 'var(--gray-gray100)',
  'bg-secondary': 'var(--white-white900)',
  'bg-item-default': 'var(--white-white900)',
  'bg-item-pressed': 'var(--gray-gray100)',
  'bg-button-primary-pressed': 'var(--blue-blue800)',
  'bg-button-primary': 'var(--blue-blue600)',
  'bg-button-danger': 'var(--red-red50)',
  'bg-button-disabled': 'var(--gray-gray100)',
  'bg-button-primarysecondary': 'var(--blue-blue50)',
  'bg-button-success': 'var(--green-green50)',
  'bg-icon-accent-tertiary': 'var(--violet-violet500)',
  'bg-icon-accent-tertiary-dimmed': 'var(--violet-violet100)',
  'bg-icon-accent-secondary': 'var(--green-green600)',
  'bg-icon-accent-secondary-dimmed': 'var(--green-green100)',
  'bg-icon-accent-primary-dimmed': 'var(--blue-blue100)',
  'bg-icon-accent-primary': 'var(--blue-blue500)',
  'bg-icon-primary': 'var(--gray-gray50)',
  'bg-icon-secondary': 'var(--white-white900)',
  'bg-icon-polkadot': 'var(--pink-pink600)',
  'bg-icon-kusama': 'var(--black-black900)',
  'bg-icon-westend': 'var(--orange-orange700)',
  'bg-icon-neutral': 'var(--gray-gray600)',

  'shadow-drop-accent-primary': 'var(--blue-blue500)',
  'shadow-inner-primary': 'var(--blue-blue400)',
  'shadow-drop-secondary': 'var(--green-green600)',
  'shadow-inner-secondary': 'var(--green-green400)',
  'shadow-drop-tertiary': 'var(--violet-violet500)',
  'shadow-inner-tertiary': 'var(--violet-violet400)',
};
