name: Create tag on Push to Main

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CREATE_TAG_PAT }}

      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Read package.json
        run: |
          echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV

      - name: Put text version to env
        run: |
          echo "${{ fromJson(env.PACKAGE_JSON).version }}"
          echo "PACKAGE_VERSION=${{ format('{0}{1}', 'v', fromJson(env.PACKAGE_JSON).version) }}" >> $GITHUB_ENV

      - name: Create new tag
        if: ${{ steps.previoustag.outputs.tag != env.PACKAGE_VERSION }}
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: v${{ fromJson(env.PACKAGE_JSON).version }}
