name: Run test in PR

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:

permissions:
  pull-requests: write
  checks: write

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Type checking
        run: npm run typecheck

      - name: Linting
        run: npm run lint

      - name: Run test
        run: npm run test:ci

      - name: Post results
        uses: davelosert/vitest-coverage-report-action@v2
